### ISSUE TITLE
User Signup & Login

### ISSUE THREAD

**Issue by matbi** [MCSPitaya/PitayaServer#17]
User Story: As a lawyer, I want to sign up / login to my own account so that only I can access confidential case files

**Comment by ksmonkey123** [comment]
Basic Implementation with JWT Bearer Tokens completed. Tested locally using curl.
Allows People to log in using their username or their email.

- Registration: `curl -X POST --data '{"username":"test", "name":"Test User", "email":"test@test.com", "password":"password"}' -H "Content-Type: application/json" http://localhost:8080/auth/register`
- Login: `curl -X POST --data '{"usernameOrEmail":"test", "password":"password"}' -H "Content-Type: application/json" http://localhost:8080/auth/login`
- Accessing user data: `curl -H "authToken: Bearer %TOKEN%" http://localhost:8080/user/me`
- Checking if a username is free: `curl http://localhost:8080/auth/usernameAvailable?username=%USER%`
- Checking if an email address is free: `curl http://localhost:8080/auth/emailAvailable?email=%EMAIL%`

**Comment by ksmonkey123** [comment]
Authentication needs to be smarter and more secure.
