### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by matbi** [MCSPitaya/PitayaServer#24]
User Story: As a lawyer, I want to receive email notifications when I‘m not in the application so I can stay up to date on all cases

**Comment by ksmonkey123** [comment]
@wozuo is this really relevant? I dont think eMail is not too desired.

**Comment by ksmonkey123** [comment]
I am asking because the prof did recommend us not do do it

**Comment by wozuo** [comment]
True, lets remove this one then.
