### ISSUE TITLE
API Endpoints 

### ISSUE THREAD

**Issue by matbi** [MCSPitaya/PitayaServer#25]
Define API Endpoints & Interface between server and Angular

**Comment by ksmonkey123** [comment]
started API Enpoint document in google drive

**Comment by ksmonkey123** [comment]
https://docs.google.com/document/d/1JDF-UgltMgblpOXm8hMZe_tic2DL-qT9_6wn5b9F5Ac/edit?usp=sharing

**Comment by ksmonkey123** [comment]
Base Endpoints are standing, more will be added as needed for the remaining user stories or on request by the frontend team. Please always keep endpoint document up to date
