### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by matbi** [MCSPitaya/PitayaServer#3]
User Story: As a lawyer, I want to receive notifications so that I can instantly see changes to case files

**Comment by ksmonkey123** [comment]
Central Activity Tracking Table that can be filtered and requested with pagination. Base Framework rather simple, tracking must be added to every (relevant) endpoint

**Comment by ksmonkey123** [comment]
Added This ticket to the sprint as it is essentially a duplicate of #4 and is more accurate than that one

**Comment by ksmonkey123** [comment]
file functions now create notifications. Therefore all relevant actions currently present have notifications. More can be added as needed
